export default [
	{ name: "Index", path: "/", component: () => import('#/Index.vue')},
]

/*
	{ name: "Accordion", path: "/accordion", component: () => import('#/Accordion.vue') },
	{ name: "Alert", path: "/alert", component: () => import('#/Alert.vue') },
	{ name: "Avatar", path: "/avatar", component: () => import('#/Avatar.vue') },
	{ name: "Badge", path: "/badge", component: () => import('#/Badge.vue') },
	{ name: "Billboard", path: "/billboard", component: () => import('#/Billboard.vue') },
	{ name: "Breadcrumb", path: "/breadcrumb", component: () => import('#/Breadcrumb.vue') },
	{ name: "Button", path: "/button", component: () => import('#/Button.vue') },
	{ name: "Calendar Tile", path: "/calendar-tile", component: () => import('#/CalendarTile.vue') },
	{ name: "Call to Action", path: "/call-to-action", component: () => import('#/CallToAction.vue') },
	{ name: "Card", path: "/card", component: () => import('#/Card.vue') },
	{ name: "Checkbox", path: "/checkbox", component: () => import('#/Checkbox.vue') },
	{ name: "Dialog", path: "/dialog", component: () => import('#/Dialog.vue') },
	{ name: "Disclosure", path: "/disclosure", component: () => import('#/Disclosure.vue') },
	{ name: "Dropdown", path: "/dropdown", component: () => import('#/Dropdown.vue') },
	{ name: "Empty State", path: "/empty-state", component: () => import('#/EmptyState.vue') },
	{ name: "File Input", path: "/file-input", component: () => import('#/FileInput.vue') },
	{ name: "Footer", path: "/footer", component: () => import('#/Footer.vue') },
	{ name: "Grid", path: "/grid", component: () => import('#/Grid.vue') },
	{ name: "Header", path: "/header", component: () => import('#/Header.vue') },
	{ name: "Hero", path: "/hero", component: () => import('#/Hero.vue') },
	{ name: "Input Group", path: "/input-group", component: () => import('#/InputGroup.vue') },
	{ name: "Link Hub", path: "/link-hub", component: () => import('#/LinkHub.vue') },
	{ name: "List", path: "/list", component: () => import('#/List.vue') },
	{ name: "Loading Indicator", path: "/loading-indicator", component: () => import('#/LoadingIndicator.vue') },
	{ name: "Pagination", path: "/pagination", component: () => import('#/Pagination.vue') },
	{ name: "Quote", path: "/quote", component: () => import('#/Quote.vue') },
	{ name: "Radio Input", path: "/radio-input", component: () => import('#/RadioInput.vue') },
	{ name: "Select Input", path: "/select-input", component: () => import('#/SelectInput.vue') },
	{ name: "Series Input", path: "/series-input", component: () => import('#/SeriesInput.vue') },
	{ name: "Series Nav", path: "/series-nav", component: () => import('#/SeriesNav.vue') },
	{ name: "Sidenav", path: "/sidenav", component: () => import('#/Sidenav.vue') },
	{ name: "Stat", path: "/stat", component: () => import('#/Stat.vue') },
	{ name: "Step Indicator", path: "/step-indicator", component: () => import('#/StepIndicator.vue') },
	{ name: "Subnav", path: "/subnav", component: () => import('#/Subnav.vue') },
	{ name: "Table", path: "/table", component: () => import('#/Table.vue') },
	{ name: "Tab", path: "/tab", component: () => import('#/Tab.vue') },
	{ name: "Text Input", path: "/text-input", component: () => import('#/TextInput.vue') },
	{ name: "Text Region", path: "/text-box", component: () => import('#/TextBox.vue') },
	{ name: "Timeline", path: "/timeline", component: () => import('#/Timeline.vue') },
	{ name: "Catch All", path: "/:catchAll(.*)", component: () => import('#/CatchAll.vue')}
*/